# Application
spring.application.name=bancom-api
server.port=8005

# Datasource - H2
#spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:bancomdb
spring.datasource.username=usrdemo
spring.datasource.password=demo
spring.datasource.driver-class-name=org.h2.Driver

# Logging
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=ERROR

# Actuator - Health check
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
management.health.defaults.enabled=true

# JWT Configuration
jwt.secret.key=my-default-secret-key-for-jwt-token-generation-and-validation-must-be-at-least-256-bits-long
jwt.expiration.time=3600000